; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:smcr]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = 
	-std=c++17
	-Os
	-fdata-sections
	-ffunction-sections
lib_archive = yes
lib_deps = 
	bblanchon/ArduinoJson@^7.4.2
	esp32async/ESPAsyncWebServer
	esp32async/AsyncTCP
	knolleary/PubSubClient